server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/usejpa1-jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug